# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161130_1348'),
        ('forum', '0002_auto_20161123_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-publish_time']},
        ),
        migrations.AddField(
            model_name='answer',
            name='reply_author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.MyUser'),
        ),
    ]
