# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='invitable',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./user/photo/%Y/%m/%d'),
        ),
    ]
